baseURL = "https://dawissl.github.io/"
languageCode = "cs-cz"
defaultContentLanguage = "cs"
title = "Můj blog"
theme = "blog-awesome"
enableRobotsTXT = true


[params]
  ShowReadingTime = true
  ShowPostNavLinks = true
  goToTop = true
  bioName = "Bc. David Sládeček"
  bioDescription = "Osobní blog, kde sdílím články, poznámky a myšlenky."
  bioImage = "/images/foto.jpg"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/dawissl"

[outputs]
  home = ["HTML", "RSS"]
  
[[menu.main]]
  identifier = "home"
  name = "Domů"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "about"
  name = "O mně"
  url = "/about/"
  weight = 10
 
