baseURL = "https://dawissl.github.io/"
languageCode = "cs-cz"
defaultContentLanguage = "cs"
title = "David Sládeček"
theme = "blog-awesome"
enableRobotsTXT = true


[params]

  ShowReadingTime = true
  ShowPostNavLinks = true
  goToTop = true

  [params.author]
    avatar = "images/foto.jpg"
    name = "Bc. David Sládeček"
    intro = "Osobní blog"
    description = "Sdílím články, poznámky a myšlenky."

[[params.socialIcons]]
  name = "github"
  url = "https://github.com/dawissl"


[outputs]
  home = ["HTML", "RSS"]
  
[[menu.main]]
  identifier = "home"
  name = "Domů"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "about"
  name = "O mně"
  url = "/about/"
  weight = 10
 
